version: '3.8'

services:
  backend:
    build: ./EasyHealth_backend
    ports:
      - "3000:3000"
    volumes:
      - ./EasyHealth_backend:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/easyhealth
    depends_on:
      - mongo

  frontend:
    build: ./EasyHealth_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./EasyHealth_frontend:/app

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
